# Generated by Django 4.2 on 2024-01-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, max_length=255, null=True)),
                ('adress', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('medical_history', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
    ]
