# Generated by Django 4.2 on 2024-03-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nurses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='on_vacation',
            field=models.CharField(default='NO', max_length=255),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='test_ordered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='tests_pending',
            field=models.IntegerField(default=0),
        ),
    ]
