# Generated by Django 4.2 on 2024-03-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0003_alter_doctor_email'),
        ('Nurses', '0002_alter_nurse_on_vacation_alter_nurse_test_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplecollector',
            name='Nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Nurses.nurse'),
        ),
        migrations.AddField(
            model_name='samplecollector',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patientsesss.patient'),
        ),
        migrations.AddField(
            model_name='samplecollector',
            name='Test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctores.test'),
        ),
        migrations.AlterUniqueTogether(
            name='samplecollector',
            unique_together={('Nurse', 'Test')},
        ),
    ]
