# Generated by Django 4.2 on 2024-01-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patientsesss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('docid', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(default='C:\\Users\\Laptop Castle\\PycharmProjects\\pythonProject3\\static\\Screenshot 2023-12-05 020734.png', upload_to='images/')),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=255)),
                ('test_name', models.CharField(max_length=255)),
                ('order_status', models.CharField(max_length=255,default='Unordered',null=False,blank=True)),
                ('cost', models.FloatField()),

            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_And_Time', models.DateTimeField()),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.doctor')),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patientsesss.patient')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
