# Generated by Django 4.2 on 2024-03-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patientsesss', '0002_alter_patient_date_of_birth'),
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='visit',
            field=models.TextField(blank=True, null=True, verbose_name='Purpose_of_Visit'),
        ),
        migrations.AlterUniqueTogether(
            name='appointments',
            unique_together={('Patient_ID', 'Doctor_ID')},
        ),
        migrations.AlterModelTable(
            name='test',
            table='Test',
        ),
    ]
